[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
